### ISSUE TITLE
You can message a group with no contacts

### ISSUE THREAD

**Issue by afomera** [king601/MessageMe#3]
If you try and message a group with no contacts it'll work... or it says it works but in reality it doesn't. 

This should be fixed

**Comment by afomera** [comment]
Creating a group message when over your quota actually shows like it works, but it rolls back and doesn't work.

**Comment by nynhex** [comment]
You may have to handle some of the logic in the controller, but we should try to duplicate this and debug.

**Comment by afomera** [comment]
Honestly, the best course of action may be to refactor the way Group Messages are sent via the messages controller. I'm not sure how just yet though.
